services:
  xbot:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xbot
    volumes:
      - ./auth:/app/auth
    restart: always
    env_file:
      - .env
